### ISSUE TITLE
Not compatible with FirewallD on Fedora

### ISSUE THREAD

**Issue by aturn3** [crasm/vpnshift.sh#1]
TLS Handshake fails when attempting to start OpenVPN. Using Astrill .ovpn client configuration file. Help would be appreciated, less familiar with networking.

**Comment by crasm** [comment]
Can you post your log file? It's /var/log/vpnshift/openvpn.log. (Make sure there's nothing sensitive first, though.)

**Comment by aturn3** [comment]
I have attached my log. I redacted my IP address.
[log.txt](https://github.com/crasm/vpnshift.sh/files/420358/log.txt)

**Comment by crasm** [comment]
It looks like the packets aren't being forwarded (no internet).

I put up a version that doesn't launch openvpn, but just sets up the environment that openvpn would use to connect: https://github.com/crasm/vpnshift.sh/blob/without-vpn/vpnshift

Can you run: 
```
$ vpnshift
$ ping duckduckgo.com
$ traceroute duckduckgo.com  # You may need to install this one
```

**Comment by aturn3** [comment]
Ping errors saying name or service not known. Seems like a DNS issue inside of the network namespace?

**Comment by aturn3** [comment]
Yea DNS issue. I can ping by IP address but not name

**Comment by crasm** [comment]
What distro are you using? What's your `uname -a`? (Red Hat?)

The nameservers mentioned in the README are written to `/etc/netns/vpnshift/resolv.conf` once the namespace is set up.

The part that's probably breaking could be whatever is managing connections. I'm using NetworkManager on Arch Linux.

**Comment by aturn3** [comment]
Fedora. OS is GNU/Linux and kernel release (if that matters in this case) is 4.5.5-300.fc24.x86_64.

**Comment by aturn3** [comment]
Turns out Fedora also uses NetworkManager. Hmm, I will have to work on potentially updating drivers or playing around with the name servers. If you can think of anything that would fix let me know! Thanks for all of the help!

**Comment by crasm** [comment]
One possibility is that NetworkManeger is configured to use a local DNS resolver like named (BIND) or unbound, so resolv.conf is never read -- but I don't think that's enabled by default.

It'll be hard to say until I try to set it up myself... I'll spin up a fedora VM and fiddle with it when I have time.

**Comment by crasm** [comment]
I went ahead and set up a VM. It looks like the default iptables firewall configuration is considerably more complicated than arch (which is... empty). Try `$ iptables --list` to see them all.

On the bright side:
- Definitely not driver related.
- Probably not nameserver related. resolv.conf was set to my nameserver correctly.

**Comment by aturn3** [comment]
Ah ok so seems like I will have to look into the firewall rules and see if I can figure things out. Thanks for all of the hassle you've gone through

**Comment by aturn3** [comment]
https://www.atlantic.net/community/howto/fedora-20-use-iptables-instead-of-firewalld/

Apparently Fedora doesn't even use the iptables by default but uses firewalld

**Comment by crasm** [comment]
That could explain some things, although I'm not sure how you were able to ping outside IPs unless the iptables NAT command worked somehow.

**Comment by crasm** [comment]
Also looks like arch doesn't come with iptables by default -- it's just what I installed since the vpnns script used it.

I'm investigating if switching iptables out for something else could help.

**Comment by aturn3** [comment]
Iptables isn't even running checking ps. Firewalld is. I will close this so it doesn't look like a bug of your script! I'll work on getting this script working but with firewalld instead of iptables

**Comment by crasm** [comment]
From what I can tell, iptables doesn't require a daemon -- it just calls into the netlink kernel API. I'd like to rewrite this in something that's not bash and use the netlink API directly. That might work better cross-distro.

To get this to work in firewalld, I think you would need to add `veth_default` to a zone and then enable masquerading (NAT) on that. (see: https://serverfault.com/questions/623297/firewalld-centos-7-masquerading)

**Comment by crasm** [comment]
Just confirmed that if you stop firewalld, vpnshift works.
```
sudo systemctl stop firewalld
```

**Comment by aturn3** [comment]
Well, that's good to know! I wouldn't feel comfortable disabling it tho as it is the primary firewall for fedora.

**Comment by crasm** [comment]
@aturn3 Can you verify #2 fixes your issue on Fedora?

**Comment by aturn3** [comment]
Yes, this is confirmed, #2 fixes my issue. Thanks!
