### ISSUE TITLE
Debugging `waiting for openvpn....`

### ISSUE THREAD

**Issue by taohansen** [crasm/vpnshift.sh#6]
My logs don't show any errors. Here's the last bit with the `Closing socket` coming after a SIGTERM.

`Tue Jan 31 22:36:33 2017 us=233632 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1604,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,cipher AES-256-CBC,auth SHA512,keysize 256,key-method 2,tls-server'
Tue Jan 31 22:36:33 2017 us=233644 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.170.11:443
Tue Jan 31 22:36:33 2017 us=233660 Socket Buffers: R=[87380->87380] S=[16384->16384]
Tue Jan 31 22:36:33 2017 us=233666 Attempting to establish TCP connection with [AF_INET]46.166.170.11:443 [nonblock]
Tue Jan 31 22:38:26 2017 us=154545 TCP/UDP: Closing socket
Tue Jan 31 22:38:26 2017 us=154599 SIGINT[hard,init_instance] received, process exiting`

**Comment by taohansen** [comment]
Running `openvpn` on its own gives me enough to debug.

**Comment by crasm** [comment]
Was it a problem with your openvpn config?

**Comment by taohansen** [comment]
It was, silly me! I don't know if this is a ridiculous feature request but I would like if vpnshift spat out the same messages openvpn was providing.

**Comment by crasm** [comment]
Yeah, the logfile is inconvenient. I switched to just letting openvpn log to stderr.
