### ISSUE TITLE
Can't connect to VPN

### ISSUE THREAD

**Issue by astrodad** [crasm/vpnshift.sh#8]
Hi, 

This is a bit new to me, but I'm trying to use this on Ubuntu 16.10 and it seems to get stuck at here:

Fri Nov  3 10:58:36 2017 OpenVPN 2.3.11 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Fri Nov  3 10:58:36 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Nov  3 10:58:36 2017 WARNING: file '/etc/openvpn/ovpn_tcp/passtxt' is group or others accessible
Fri Nov  3 10:58:36 2017 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Fri Nov  3 10:58:36 2017 Control Channel Authentication: tls-auth using INLINE static key file
Fri Nov  3 10:58:36 2017 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Nov  3 10:58:36 2017 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Nov  3 10:58:36 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Nov  3 10:58:36 2017 UDPv4 link local: [undef]
Fri Nov  3 10:58:36 2017 UDPv4 link remote: [AF_INET]173.209.53.188:1194

This is for NordVPN server in CA, which I can ping no problems and works from other clients. Any ideas where to start troubleshooting?

**Comment by crasm** [comment]
I'm not doing anything funky with respect to openvpn, so you should try calling openvpn directly without vpnshift:
```
sudo openvpn --config <path/to/config>
```

If that doesn't work, then the problem is with your config or client (or potentially the remote). If it does work, drop a comment and I'll reopen this and see if I can take a look.
