### ISSUE TITLE
Network unreachable : autonegotiation error

### ISSUE THREAD

**Issue by joachimesque** [crasm/vpnshift.sh#9]
Hi,

I've been trying to have vpnshift working on my machine, but I've got this problem when setting up the veth tunnel (line 152)

    must ip link add "${veth_vpn}" type veth peer name "${veth_default}"

Here's the relevant portion in `journalctl -xe`

```
nov. 21 14:28:59 compy9000 systemd-udevd[1428]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
nov. 21 14:28:59 compy9000 systemd-udevd[1430]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
nov. 21 14:28:59 compy9000 systemd-udevd[1430]: link_config: could not get ethtool features for veth_vpn
nov. 21 14:28:59 compy9000 systemd-udevd[1430]: Could not set offload features of veth_vpn: No such device
nov. 21 14:28:59 compy9000 kernel: IPv6: ADDRCONF(NETDEV_UP): veth_default: link is not ready
nov. 21 14:28:59 compy9000 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth_default: link becomes ready
```

I found no relevant info on Google about these problems.

**Comment by crasm** [comment]
What's your `uname -a`? I'm not getting this issue on Arch Linux 4.13.12-1-ARCH. Also, "veth_vpn" and "veth_default" are my strings so omitting those when searching might help.

**Comment by joachimesque** [comment]
Here's my system info :

    Linux compy9000 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by crasm** [comment]
Can you try `vpnshift -c <path/to/your/config> -d`? That drops you into a shell right before it starts openvpn. So in that shell you should be in the network namespace, not connected to your VPN provider, but should still have normal internet access through the veth.

Then post your `ip netns` and `ip addr` outputs.

**Comment by joachimesque** [comment]
Thanks for taking the time to answer my problem! The more I look into it, the more I think it's way deeper than I thought.

Here are the outputs to both commands:

````
root@compy9000:/etc/openvpn# ip netns
vpnshift
root@compy9000:/etc/openvpn# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
15: veth_vpn@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ad:84:be:c8:6d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.10.10.11/31 scope global veth_vpn
       valid_lft forever preferred_lft forever
    inet6 fe80::ecad:84ff:febe:c86d/64 scope link
       valid_lft forever preferred_lft forever
````

I'm having the same messages about autonegotiation, even when I try the standalone `openvpn --config /…/…`. I might decide to setup a clean environment, reinstall the OS and all that, at this point it might save me time in the long run (no, it's not the frustration / desperation speaking :) )

So if you see a solution right away don't hesitate to share, but as the problem doesn't stem from your script or a wrong use of your script by me, I won't take more of your time :)

(I'm certain your script would be perfect as a single service to call Deluge over the VPN connexion, instead of having two services (OpenVPN and Deluge))

**Comment by crasm** [comment]
I'd start by checking if you can make an openvpn connection using an entirely different config file. You can spin up a temporary VPN VM (running an openvpn daemon) pretty easily and cheaply using [streisand](https://github.com/StreisandEffect/streisand), and it gives you the .ovpn files.

If that doesn't work, then it's probably some horrifying combination of systemd/udev/<your adapter's module blob?>, and going nuclear by switching distros or installing a more up-to-date OS is your best shot.
